
import dao.connectionprovider;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.util.Date;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ADMIN
 */
public class UpdateUserr extends javax.swing.JFrame {
    private String emailpattern = "^[a-zA-Z0-9]+[@]+[a-zA-Z0-9]+[.]+[a-zA-Z0-9]+$";
    private String MobileNumberPattern = "^[0-9]*$";

    /**
     * Creates new form UpdateUserr
     */
    public UpdateUserr() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        usernametxt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        combouser = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        dateob = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        mobilentxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        addresstxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        emailtxt = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        nametxt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("USERNAME");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 91, 103, -1));

        usernametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernametxtActionPerformed(evt);
            }
        });
        getContentPane().add(usernametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 88, 234, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        jButton1.setText("SEARCH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(578, 86, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 132, 817, 10));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setText("UPDATE USER");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 260, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("USER ROLE");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 160, 183, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 336, 183, -1));

        combouser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ADMIN", "PHARMACISTS" }));
        getContentPane().add(combouser, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 188, 183, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("DOB(DATE OF BIRTH)");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 239, 183, -1));
        getContentPane().add(dateob, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 261, 183, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("NAME");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 183, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("MOBILE NUMBER");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(535, 160, 162, -1));
        getContentPane().add(mobilentxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(535, 188, 162, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("ADDRESS");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(535, 239, 162, -1));

        addresstxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addresstxtActionPerformed(evt);
            }
        });
        getContentPane().add(addresstxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(535, 261, 162, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("EMAILID");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(535, 308, 162, -1));
        getContentPane().add(emailtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(535, 336, 162, -1));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        jButton2.setText("UPDATE USER");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 420, -1, -1));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 10, -1, -1));

        nametxt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/all_pages_background.png"))); // NOI18N
        nametxt.setText("jLabel10");
        getContentPane().add(nametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernametxtActionPerformed

    private void addresstxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addresstxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addresstxtActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int checkuserexist = 0;
        String username = usernametxt.getText();
        if(username.equals("")){
            JOptionPane.showMessageDialog(null, "username Field is requires ");
        }else{
            SimpleDateFormat dformat = new SimpleDateFormat("dd-MM-YYYY");
            try{
                Connection con = connectionprovider.getcon();
                Statement st = con.createStatement();
                ResultSet rs = st.executeQuery("SELECT * FROM appuser WHERE username = '" + username + "'");

                while(rs.next()){
                    usernametxt.setEditable(false);
                    checkuserexist = 1;
                    nametxt.setText(rs.getString("name"));
                    mobilentxt.setText(rs.getString("mobilenumber"));
                    emailtxt.setText(rs.getString("email"));
                    addresstxt.setText(rs.getString("address"));
                    String dob = rs.getString("dob");
                    if(dob != ""){
                        try{
                            dateob.setDate(dformat.parse(dob));
                        
                        }
                        catch(Exception e){
                             JOptionPane.showMessageDialog(null, e);
                        }
                    }
                    if(rs.getString("userrole").equals("ADMIN")){
                        combouser.removeAllItems();
                        combouser.addItem("ADMIN");
                        combouser.addItem("PHARMACISTS");
                    }else{
                        combouser.removeAllItems();
                        combouser.addItem("PHARMACISTS");
                        combouser.addItem("admin");
                    }
                    
                }
                
            
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
            if(checkuserexist == 0){
                JOptionPane.showMessageDialog(null, "username name doesnot exist");
            }
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String userrole = (String) combouser.getSelectedItem();
        String name = nametxt.getText();
        SimpleDateFormat dformat = new SimpleDateFormat("dd-MM-yyyy");
        Date dob = dateob.getDate();
        String dobb = "";
        if (dateob != null) {
            dobb = dformat.format(dateob.getDate());
        }
        String username = usernametxt.getText();
        String address = addresstxt.getText();
        String mobilenumber = mobilentxt.getText();
        String email = emailtxt.getText();
        
        int checkuserexist = 0; 
        
        if (name.equals("")) {
            JOptionPane.showMessageDialog(null, "name field is requied");
        }else if(dobb.equals("")){
            JOptionPane.showMessageDialog(null, "date of birth field is requied");
        }else if(mobilenumber.equals("")){
            JOptionPane.showMessageDialog(null, "mobile number field is requied");
        }else if(mobilenumber.length() != 10 || !mobilenumber.matches(MobileNumberPattern)){
            JOptionPane.showMessageDialog(null, "Mobile number is invalid");
        }else if(email.equals("")){
            JOptionPane.showMessageDialog(null, "email id field is requied");
        }else if(!email.matches(emailpattern)){
            JOptionPane.showMessageDialog(null, "email id is invalid");
        }else if(username.equals("")){
            JOptionPane.showMessageDialog(null, "username field is requied");
        }else if(address.equals("")){
            JOptionPane.showMessageDialog(null, "address field is requied");
        }else{
            try{
                Connection con = connectionprovider.getcon();
                 PreparedStatement ps = con.prepareStatement("update appuser set userrole = ?,name=?,dob=?,mobilenumber=?,email=?,address=? where username=?");
                 
                 ps.setString(1, userrole);
                 ps.setString(2, name);
                 ps.setString(3, dobb);
                 ps.setString(4, mobilenumber);
                 ps.setString(5, email);
                 ps.setString(6, address);
                 ps.setString(7, username);
                 ps.executeUpdate();
                JOptionPane.showMessageDialog(null, "user added successfully");
                setVisible(false);
                new UpdateUserr().setVisible(true);
                 
            
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateUserr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateUserr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateUserr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateUserr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateUserr().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addresstxt;
    private javax.swing.JComboBox<String> combouser;
    private com.toedter.calendar.JDateChooser dateob;
    private javax.swing.JTextField emailtxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField mobilentxt;
    private javax.swing.JLabel nametxt;
    private javax.swing.JTextField usernametxt;
    // End of variables declaration//GEN-END:variables
}
